- src/org/zowe/pipelines/NodeJS.groovy
Add email notifications to pipeline in new end() method
> Add email notifications

- src/org/zowe/pipelines/NodeJS.groovy
After testing, this now catches `error` statements and correctly detects failure of the build
> Fix error catching for email result

- docs/JenkinsPipeline.md
- docs/ManualProcess.md
Grammar review for the Manual process article.
> # 135 document and test future scripts/procedures for lts incremental & stable

- src/org/zowe/pipelines/nodejs/NodeJSPipeline.groovy
> I have no words for this :/

- scripts/README.md
- scripts/code-migration.groovy
- scripts/hello.sh
Signed-off-by: zFernand0 <Fernando.RijoCedeno@broadcom.com>
> add code-migration

- src/org/zowe/pipelines/nodejs/NodeJSPipeline.groovy
- package name now shows on timeout emails
- registry url now shows on customLogin deployments
> Fix small issues

- scripts/deploy-zowe-cli-all.groovy
Signed-off-by: Colin-Stone <30794003+Colin-Stone@users.noreply.github.com>
> Now MQ is the new kid on the block

- src/org/zowe/pipelines/nodejs/NodeJSPipeline.groovy
> Add release registry

- src/org/zowe/pipelines/base/Pipeline.groovy
- src/org/zowe/pipelines/nodejs/NodeJSPipeline.groovy
- src/org/zowe/pipelines/nodejs/models/DependencyDefinition.groovy
- src/org/zowe/pipelines/nodejs/models/NodeJSProtectedBranch.groovy
Fixes #51 
Allowing specific registries to be specified for each dependency (finally)
> Add dep reg

- src/org/zowe/pipelines/nodejs/NodeJSPipeline.groovy
- src/org/zowe/pipelines/nodejs/models/NodeJSProtectedBranch.groovy
Also fix a bug where package name and version could be `null`
> Support creation of alias tags on NPM

- src/org/zowe/pipelines/nodejs/NodeJSPipeline.groovy
> Always apply alias tags, even if no new version was published

- src/org/zowe/pipelines/generic/GenericPipeline.groovy
- src/org/zowe/pipelines/nodejs/NodeJSPipeline.groovy
> Allow same version

- src/org/zowe/pipelines/generic/arguments/GenericStageArguments.groovy
- src/org/zowe/pipelines/generic/arguments/VersionStageArguments.groovy
- src/org/zowe/pipelines/generic/models/GenericPipelineControl.groovy
- src/org/zowe/pipelines/nodejs/NodeJSPipeline.groovy
- src/org/zowe/pipelines/nodejs/arguments/CheckVulnerabilitiesStageArguments.groovy
- src/org/zowe/pipelines/nodejs/arguments/DeployStageArguments.groovy
- src/org/zowe/pipelines/nodejs/arguments/LintStageArguments.groovy
> Linter stage and version label

- src/org/zowe/pipelines/generic/arguments/BuildStageArguments.groovy
- src/org/zowe/pipelines/nodejs/NodeJSPipeline.groovy
fixes #80
Signed-off-by: zFernand0 <fernando.rijocedeno@broadcom.com>
> Add archive operation

- .gitignore
- deploy-constants.yaml
> Deploy Secure Credential Store plugin to NPM

- scripts/deploy-zowe-cli-component.groovy
> Fix error "Tag name must not be a valid SemVer range"

- src/org/zowe/pipelines/nodejs/NodeJSPipeline.groovy
> Add missing steps.

- src/org/zowe/pipelines/generic/GenericPipeline.groovy
- src/org/zowe/pipelines/generic/arguments/ChangelogStageArguments.groovy
- src/org/zowe/pipelines/nodejs/NodeJSPipeline.groovy
> Add changelog update skip logic

- src/org/zowe/pipelines/nodejs/NodeJSPipeline.groovy
> Fix DCO Signoff

- src/org/zowe/pipelines/generic/GenericPipeline.groovy
> Compare against change target.

- src/org/zowe/pipelines/nodejs/NodeJSPipeline.groovy
> Remove extra ci-skip

- src/org/zowe/pipelines/generic/GenericPipeline.groovy
> Change the changelog parser to only look at Zowe repos.

- scripts/generate-npm-report.groovy
Signed-off-by: MarkAckert <mark.ackert@broadcom.com>
> update repository target

- src/org/zowe/pipelines/nodejs/NodeJSPipeline.groovy
- src/org/zowe/pipelines/nodejs/arguments/CheckVulnerabilitiesStageArguments.groovy
Working pipeline
https://wash.zowe.org:8443/blue/organizations/jenkins/imperative/detail/master/441/pipeline/188
> Audit-level moderate by default

- src/org/zowe/pipelines/generic/GenericPipeline.groovy
- src/org/zowe/pipelines/generic/arguments/ChangelogStageArguments.groovy
- src/org/zowe/pipelines/nodejs/NodeJSPipeline.groovy
> More monorepo fixes (changelog and vuln checks)

- src/org/zowe/pipelines/nodejs/NodeJSPipeline.groovy
> Don't create npm-shrinkwrap before publish

- src/org/zowe/pipelines/nodejs/NodeJSPipeline.groovy
Signed-off-by: zFernand0 <fernando.rijocedeno@broadcom.com>
Fix #113
> Fix Timeout Version Selection

- deploy-constants.yaml
> Publish "next" release of SDKs

- src/org/zowe/pipelines/nodejs/NodeJSPipeline.groovy
> Fix reporting of Sonar version for monorepo

- src/org/zowe/pipelines/nodejs/NodeJSPipeline.groovy
- src/org/zowe/pipelines/nodejs/arguments/NodeJSSonarScanArguments.groovy
Add ability to use sonarScan with customized credentials instead of only allowing withSonarQubeEnv
> Sonarscan update

- deploy-constants.yaml
> Publish next tag for CICS/DB2/IMS/MQ

- deploy-constants.yaml
> Publish next tag for tasks and zos-make

- src/org/zowe/pipelines/nodejs/NodeJSPipeline.groovy
- src/org/zowe/pipelines/nodejs/arguments/DeployStageArguments.groovy
Add smoke test that runs after package is published to staging repo
> Smoke test part 1

- scripts/deploy-zowe-cli-component.groovy
- scripts/repackage_tar.sh
ℹ️ It may be easier to review this PR with whitespace changes hidden 🙂 
* Before publishing package:
* Check that package dependencies are valid (since NPM doesn't do this)
* After publishing package
* Wait for new version to show up on registry
* Try to install new version from registry
* If install failed, revert package tag to point to last good version
These changes have been tested with an internal registry. I can provide more info if desired 😛
> Smoke test part 2

- src/org/zowe/pipelines/nodejs/NodeJSPipeline.groovy
> Fix package/version not being updated in subdirectory

- scripts/generate-npm-report.groovy
The pipeline ran successfully here: https://wash.zowe.org:8443/blue/organizations/jenkins/zowe-cli-npm-report/detail/zowe-cli-npm-report/140/pipeline
I don't have access to see the "zowe/security-reports" repository, so commented out the lines that push a commit there for now. Once this PR is approved by someone who has access to that repo (e.g., @zFernand0 😛), we should uncomment those lines.
> Fix NPM Reporter pipeline

- deploy-constants.yaml
> Add zoslogs SDK to list of packages to deploy

- src/org/zowe/pipelines/nodejs/NodeJSPipeline.groovy
Working examples:
https://wash.zowe.org:8443/job/brightside/job/PR-1279/2/
https://wash.zowe.org:8443/job/brightside/job/PR-1280/2/
> Quick fix for shrinkwrap

- src/org/zowe/pipelines/nodejs/NodeJSPipeline.groovy
Signed-off-by: zFernand0 <fernando.rijocedeno@broadcom.com>
> do not minify package.json file

- src/org/zowe/pipelines/nodejs/NodeJSPipeline.groovy
> Remove npm set-script command that fails with npm@6

- src/org/zowe/pipelines/nodejs/NodeJSPipeline.groovy
> Fix "git add" command failing the pipeline

- src/org/zowe/pipelines/nodejs/NodeJSPipeline.groovy
- src/org/zowe/pipelines/nodejs/arguments/NodeJSSonarScanArguments.groovy
> Allow Sonar scanner tool name to be overridden
